#developed by muhammed roshan
from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
    def __init__(self):
       QtGui.QWidget.__init__(self)
       self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(689, 552)
        self.sp2 = QtGui.QSpinBox(Form)
        self.sp2.setGeometry(QtCore.QRect(420, 180, 65, 33))
        self.sp2.setObjectName(_fromUtf8("sp2"))
        self.C2 = QtGui.QComboBox(Form)
        self.C2.setGeometry(QtCore.QRect(70, 180, 311, 29))
        self.C2.setObjectName(_fromUtf8("C2"))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C2.addItem(_fromUtf8(""))
        self.C1 = QtGui.QComboBox(Form)
        self.C1.setGeometry(QtCore.QRect(70, 120, 311, 29))
        self.C1.setObjectName(_fromUtf8("C1"))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.C1.addItem(_fromUtf8(""))
        self.button = QtGui.QCommandLinkButton(Form)
        self.button.setGeometry(QtCore.QRect(490, 460, 121, 41))
        self.button.setObjectName(_fromUtf8("button"))
        self.sp5 = QtGui.QSpinBox(Form)
        self.sp5.setGeometry(QtCore.QRect(420, 360, 65, 33))
        self.sp5.setObjectName(_fromUtf8("sp5"))
        self.sp4 = QtGui.QSpinBox(Form)
        self.sp4.setGeometry(QtCore.QRect(420, 300, 65, 33))
        self.sp4.setObjectName(_fromUtf8("sp4"))
        self.C5 = QtGui.QComboBox(Form)
        self.C5.setGeometry(QtCore.QRect(70, 360, 311, 29))
        self.C5.setObjectName(_fromUtf8("C5"))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C5.addItem(_fromUtf8(""))
        self.C4 = QtGui.QComboBox(Form)
        self.C4.setGeometry(QtCore.QRect(70, 300, 311, 29))
        self.C4.setObjectName(_fromUtf8("C4"))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.C4.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 80, 65, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.C3 = QtGui.QComboBox(Form)
        self.C3.setGeometry(QtCore.QRect(70, 240, 311, 29))
        self.C3.setObjectName(_fromUtf8("C3"))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.C3.addItem(_fromUtf8(""))
        self.sp1 = QtGui.QSpinBox(Form)
        self.sp1.setGeometry(QtCore.QRect(420, 120, 65, 33))
        self.sp1.setObjectName(_fromUtf8("sp1"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(430, 80, 65, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.sp3 = QtGui.QSpinBox(Form)
        self.sp3.setGeometry(QtCore.QRect(420, 240, 65, 33))
        self.sp3.setObjectName(_fromUtf8("sp3"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "RESTAURENT MENU", None))
        self.C2.setItemText(0, _translate("Form", "Add Items", None))
        self.C2.setItemText(1, _translate("Form", "Tea", None))
        self.C2.setItemText(2, _translate("Form", "Lime Juice", None))
        self.C2.setItemText(3, _translate("Form", "Vada", None))
        self.C2.setItemText(4, _translate("Form", "Shavarma", None))
        self.C2.setItemText(5, _translate("Form", "Chappathi", None))
        self.C2.setItemText(6, _translate("Form", "Parotta", None))
        self.C2.setItemText(7, _translate("Form", "Dosa", None))
        self.C2.setItemText(8, _translate("Form", "Chicken Fry", None))
        self.C2.setItemText(9, _translate("Form", "Biriyani", None))
        self.C1.setItemText(0, _translate("Form", "Add Items", None))
        self.C1.setItemText(1, _translate("Form", "Tea", None))
        self.C1.setItemText(2, _translate("Form", "Lime Juice", None))
        self.C1.setItemText(3, _translate("Form", "Vada", None))
        self.C1.setItemText(4, _translate("Form", "Shavarma", None))
        self.C1.setItemText(5, _translate("Form", "Chappathi", None))
        self.C1.setItemText(6, _translate("Form", "Parotta", None))
        self.C1.setItemText(7, _translate("Form", "Dosa", None))
        self.C1.setItemText(8, _translate("Form", "Chicken Fry", None))
        self.C1.setItemText(9, _translate("Form", "Biriyani", None))
        self.button.setText(_translate("Form", "PLACE ORDER", None))
        self.C5.setItemText(0, _translate("Form", "Add Items", None))
        self.C5.setItemText(1, _translate("Form", "Tea", None))
        self.C5.setItemText(2, _translate("Form", "Lime Juice", None))
        self.C5.setItemText(3, _translate("Form", "Vada", None))
        self.C5.setItemText(4, _translate("Form", "Shavarma", None))
        self.C5.setItemText(5, _translate("Form", "Chappathi", None))
        self.C5.setItemText(6, _translate("Form", "Parotta", None))
        self.C5.setItemText(7, _translate("Form", "Dosa", None))
        self.C5.setItemText(8, _translate("Form", "Chicken Fry", None))
        self.C5.setItemText(9, _translate("Form", "Biriyani", None))
        self.C4.setItemText(0, _translate("Form", "Add Items", None))
        self.C4.setItemText(1, _translate("Form", "Tea", None))
        self.C4.setItemText(2, _translate("Form", "Lime Juice", None))
        self.C4.setItemText(3, _translate("Form", "Vada", None))
        self.C4.setItemText(4, _translate("Form", "Shavarma", None))
        self.C4.setItemText(5, _translate("Form", "Chappathi", None))
        self.C4.setItemText(6, _translate("Form", "Parotta", None))
        self.C4.setItemText(7, _translate("Form", "Dosa", None))
        self.C4.setItemText(8, _translate("Form", "Chicken Fry", None))
        self.C4.setItemText(9, _translate("Form", "Biriyani", None))
        self.label_2.setText(_translate("Form", "ITEM", None))
        self.C3.setItemText(0, _translate("Form", "Add Items", None))
        self.C3.setItemText(1, _translate("Form", "Tea", None))
        self.C3.setItemText(2, _translate("Form", "Lime Juice", None))
        self.C3.setItemText(3, _translate("Form", "Vada", None))
        self.C3.setItemText(4, _translate("Form", "Shavarma", None))
        self.C3.setItemText(5, _translate("Form", "Chappathi", None))
        self.C3.setItemText(6, _translate("Form", "Parotta", None))
        self.C3.setItemText(7, _translate("Form", "Dosa", None))
        self.C3.setItemText(8, _translate("Form", "Chicken Fry", None))
        self.C3.setItemText(9, _translate("Form", "Biriyani", None))
        self.label.setText(_translate("Form", "QTY", None))
        self.button.clicked.connect(self.buttonclicked)
    def buttonclicked(self):
        t1=self.C1.currentText()
        t2=self.C2.currentText()
        t3=self.C3.currentText()
        t4=self.C4.currentText()
        t5=self.C5.currentText()
        n1=self.sp1.value()
        n2=self.sp2.value()
        n3=self.sp3.value()
        n4=self.sp4.value()
        n5=self.sp5.value()
        print t1,n1 ,t2,n2,t3,n3,t4,n4,t5,n5
    


if __name__ == '__main__':
    app=QtGui.QApplication(sys.argv)
    ex=Ui_Form()
    ex.show()
    sys.exit(app.exec_())   
    

