

from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
class Ui_Form(QtGui.QWidget):
    def __init__(self):
       QtGui.QWidget.__init__(self)
       self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1028, 720)
        self.l1 = QtGui.QLabel(Form)
        self.l1.setGeometry(QtCore.QRect(90, 100, 161, 21))
        self.l1.setObjectName(_fromUtf8("l1"))
        self.l2 = QtGui.QLabel(Form)
        self.l2.setGeometry(QtCore.QRect(90, 140, 161, 21))
        self.l2.setObjectName(_fromUtf8("l2"))
        self.l4 = QtGui.QLabel(Form)
        self.l4.setGeometry(QtCore.QRect(90, 220, 161, 21))
        self.l4.setObjectName(_fromUtf8("l4"))
        self.l3 = QtGui.QLabel(Form)
        self.l3.setGeometry(QtCore.QRect(90, 180, 161, 21))
        self.l3.setObjectName(_fromUtf8("l3"))
        self.l8 = QtGui.QLabel(Form)
        self.l8.setGeometry(QtCore.QRect(90, 380, 161, 21))
        self.l8.setObjectName(_fromUtf8("l8"))
        self.l7 = QtGui.QLabel(Form)
        self.l7.setGeometry(QtCore.QRect(90, 340, 161, 21))
        self.l7.setObjectName(_fromUtf8("l7"))
        self.l5 = QtGui.QLabel(Form)
        self.l5.setGeometry(QtCore.QRect(90, 260, 161, 21))
        self.l5.setObjectName(_fromUtf8("l5"))
        self.l6 = QtGui.QLabel(Form)
        self.l6.setGeometry(QtCore.QRect(90, 300, 161, 21))
        self.l6.setObjectName(_fromUtf8("l6"))
        self.l15 = QtGui.QLabel(Form)
        self.l15.setGeometry(QtCore.QRect(560, 340, 161, 21))
        self.l15.setObjectName(_fromUtf8("l15"))
        self.l12 = QtGui.QLabel(Form)
        self.l12.setGeometry(QtCore.QRect(560, 220, 161, 21))
        self.l12.setObjectName(_fromUtf8("l12"))
        self.l11 = QtGui.QLabel(Form)
        self.l11.setGeometry(QtCore.QRect(560, 180, 161, 21))
        self.l11.setObjectName(_fromUtf8("l11"))
        self.l14 = QtGui.QLabel(Form)
        self.l14.setGeometry(QtCore.QRect(560, 300, 161, 21))
        self.l14.setObjectName(_fromUtf8("l14"))
        self.l9 = QtGui.QLabel(Form)
        self.l9.setGeometry(QtCore.QRect(560, 100, 161, 21))
        self.l9.setObjectName(_fromUtf8("l9"))
        self.l13 = QtGui.QLabel(Form)
        self.l13.setGeometry(QtCore.QRect(560, 260, 161, 21))
        self.l13.setObjectName(_fromUtf8("l13"))
        self.l16 = QtGui.QLabel(Form)
        self.l16.setGeometry(QtCore.QRect(560, 380, 161, 21))
        self.l16.setObjectName(_fromUtf8("l16"))
        self.l10 = QtGui.QLabel(Form)
        self.l10.setGeometry(QtCore.QRect(560, 140, 161, 21))
        self.l10.setObjectName(_fromUtf8("l10"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(480, 60, 20, 341))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.sp1 = QtGui.QSpinBox(Form)
        self.sp1.setGeometry(QtCore.QRect(320, 90, 65, 33))
        self.sp1.setObjectName(_fromUtf8("sp1"))
        self.sp2 = QtGui.QSpinBox(Form)
        self.sp2.setGeometry(QtCore.QRect(320, 130, 65, 33))
        self.sp2.setObjectName(_fromUtf8("sp2"))
        self.sp3 = QtGui.QSpinBox(Form)
        self.sp3.setGeometry(QtCore.QRect(320, 170, 65, 33))
        self.sp3.setObjectName(_fromUtf8("sp3"))
        self.sp4 = QtGui.QSpinBox(Form)
        self.sp4.setGeometry(QtCore.QRect(320, 210, 65, 33))
        self.sp4.setObjectName(_fromUtf8("sp4"))
        self.sp5 = QtGui.QSpinBox(Form)
        self.sp5.setGeometry(QtCore.QRect(320, 250, 65, 33))
        self.sp5.setObjectName(_fromUtf8("sp5"))
        self.sp6 = QtGui.QSpinBox(Form)
        self.sp6.setGeometry(QtCore.QRect(320, 290, 65, 33))
        self.sp6.setObjectName(_fromUtf8("sp6"))
        self.sp7 = QtGui.QSpinBox(Form)
        self.sp7.setGeometry(QtCore.QRect(320, 330, 65, 33))
        self.sp7.setObjectName(_fromUtf8("sp7"))
        self.sp8 = QtGui.QSpinBox(Form)
        self.sp8.setGeometry(QtCore.QRect(320, 370, 65, 33))
        self.sp8.setObjectName(_fromUtf8("sp8"))
        self.sp11 = QtGui.QSpinBox(Form)
        self.sp11.setGeometry(QtCore.QRect(810, 170, 65, 33))
        self.sp11.setObjectName(_fromUtf8("sp11"))
        self.sp12 = QtGui.QSpinBox(Form)
        self.sp12.setGeometry(QtCore.QRect(810, 210, 65, 33))
        self.sp12.setObjectName(_fromUtf8("sp12"))
        self.sp16 = QtGui.QSpinBox(Form)
        self.sp16.setGeometry(QtCore.QRect(810, 370, 65, 33))
        self.sp16.setObjectName(_fromUtf8("sp16"))
        self.sp14 = QtGui.QSpinBox(Form)
        self.sp14.setGeometry(QtCore.QRect(810, 290, 65, 33))
        self.sp14.setObjectName(_fromUtf8("sp14"))
        self.sp13 = QtGui.QSpinBox(Form)
        self.sp13.setGeometry(QtCore.QRect(810, 250, 65, 33))
        self.sp13.setObjectName(_fromUtf8("sp13"))
        self.sp15 = QtGui.QSpinBox(Form)
        self.sp15.setGeometry(QtCore.QRect(810, 330, 65, 33))
        self.sp15.setObjectName(_fromUtf8("sp15"))
        self.sp9 = QtGui.QSpinBox(Form)
        self.sp9.setGeometry(QtCore.QRect(810, 90, 65, 33))
        self.sp9.setObjectName(_fromUtf8("sp9"))
        self.sp10 = QtGui.QSpinBox(Form)
        self.sp10.setGeometry(QtCore.QRect(810, 130, 65, 33))
        self.sp10.setObjectName(_fromUtf8("sp10"))
        self.c1 = QtGui.QCheckBox(Form)
        self.c1.setGeometry(QtCore.QRect(410, 90, 94, 26))
        self.c1.setText(_fromUtf8(""))
        self.c1.setObjectName(_fromUtf8("c1"))
        self.c2 = QtGui.QCheckBox(Form)
        self.c2.setGeometry(QtCore.QRect(410, 130, 94, 26))
        self.c2.setText(_fromUtf8(""))
        self.c2.setObjectName(_fromUtf8("c2"))
        self.c3 = QtGui.QCheckBox(Form)
        self.c3.setGeometry(QtCore.QRect(410, 170, 94, 26))
        self.c3.setText(_fromUtf8(""))
        self.c3.setObjectName(_fromUtf8("c3"))
        self.c4 = QtGui.QCheckBox(Form)
        self.c4.setGeometry(QtCore.QRect(410, 210, 94, 26))
        self.c4.setText(_fromUtf8(""))
        self.c4.setObjectName(_fromUtf8("c4"))
        self.c7 = QtGui.QCheckBox(Form)
        self.c7.setGeometry(QtCore.QRect(410, 330, 94, 26))
        self.c7.setText(_fromUtf8(""))
        self.c7.setObjectName(_fromUtf8("c7"))
        self.c6 = QtGui.QCheckBox(Form)
        self.c6.setGeometry(QtCore.QRect(410, 290, 94, 26))
        self.c6.setText(_fromUtf8(""))
        self.c6.setObjectName(_fromUtf8("c6"))
        self.c8 = QtGui.QCheckBox(Form)
        self.c8.setGeometry(QtCore.QRect(410, 370, 94, 26))
        self.c8.setText(_fromUtf8(""))
        self.c8.setObjectName(_fromUtf8("c8"))
        self.c5 = QtGui.QCheckBox(Form)
        self.c5.setGeometry(QtCore.QRect(410, 250, 94, 26))
        self.c5.setText(_fromUtf8(""))
        self.c5.setObjectName(_fromUtf8("c5"))
        self.c16 = QtGui.QCheckBox(Form)
        self.c16.setGeometry(QtCore.QRect(910, 370, 94, 26))
        self.c16.setText(_fromUtf8(""))
        self.c16.setObjectName(_fromUtf8("c16"))
        self.c11 = QtGui.QCheckBox(Form)
        self.c11.setGeometry(QtCore.QRect(910, 170, 94, 26))
        self.c11.setText(_fromUtf8(""))
        self.c11.setObjectName(_fromUtf8("c11"))
        self.c10 = QtGui.QCheckBox(Form)
        self.c10.setGeometry(QtCore.QRect(910, 130, 94, 26))
        self.c10.setText(_fromUtf8(""))
        self.c10.setObjectName(_fromUtf8("c10"))
        self.c13 = QtGui.QCheckBox(Form)
        self.c13.setGeometry(QtCore.QRect(910, 250, 94, 26))
        self.c13.setText(_fromUtf8(""))
        self.c13.setObjectName(_fromUtf8("c13"))
        self.c12 = QtGui.QCheckBox(Form)
        self.c12.setGeometry(QtCore.QRect(910, 210, 94, 26))
        self.c12.setText(_fromUtf8(""))
        self.c12.setObjectName(_fromUtf8("c12"))
        self.c9 = QtGui.QCheckBox(Form)
        self.c9.setGeometry(QtCore.QRect(910, 90, 94, 26))
        self.c9.setText(_fromUtf8(""))
        self.c9.setObjectName(_fromUtf8("c9"))
        self.c14 = QtGui.QCheckBox(Form)
        self.c14.setGeometry(QtCore.QRect(910, 290, 94, 26))
        self.c14.setText(_fromUtf8(""))
        self.c14.setObjectName(_fromUtf8("c14"))
        self.c15 = QtGui.QCheckBox(Form)
        self.c15.setGeometry(QtCore.QRect(910, 330, 94, 26))
        self.c15.setText(_fromUtf8(""))
        self.c15.setObjectName(_fromUtf8("c15"))
        self.total = QtGui.QPushButton(Form)
        self.total.setGeometry(QtCore.QRect(300, 500, 121, 31))
        self.total.setObjectName(_fromUtf8("total"))
        self.lcd = QtGui.QLCDNumber(Form)
        self.lcd.setGeometry(QtCore.QRect(470, 500, 131, 31))
        self.lcd.setObjectName(_fromUtf8("lcd"))
        self.order = QtGui.QCommandLinkButton(Form)
        self.order.setGeometry(QtCore.QRect(710, 600, 131, 31))
        self.order.setObjectName(_fromUtf8("order"))
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(440, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.p1 = QtGui.QLabel(Form)
        self.p1.setGeometry(QtCore.QRect(200, 100, 65, 21))
        self.p1.setObjectName(_fromUtf8("p1"))
        self.p3 = QtGui.QLabel(Form)
        self.p3.setGeometry(QtCore.QRect(200, 180, 65, 21))
        self.p3.setObjectName(_fromUtf8("p3"))
        self.p2 = QtGui.QLabel(Form)
        self.p2.setGeometry(QtCore.QRect(200, 140, 65, 21))
        self.p2.setObjectName(_fromUtf8("p2"))
        self.p5 = QtGui.QLabel(Form)
        self.p5.setGeometry(QtCore.QRect(200, 260, 65, 21))
        self.p5.setObjectName(_fromUtf8("p5"))
        self.p4 = QtGui.QLabel(Form)
        self.p4.setGeometry(QtCore.QRect(200, 220, 65, 21))
        self.p4.setObjectName(_fromUtf8("p4"))
        self.p6 = QtGui.QLabel(Form)
        self.p6.setGeometry(QtCore.QRect(200, 300, 65, 21))
        self.p6.setObjectName(_fromUtf8("p6"))
        self.p7 = QtGui.QLabel(Form)
        self.p7.setGeometry(QtCore.QRect(200, 340, 65, 21))
        self.p7.setObjectName(_fromUtf8("p7"))
        self.p8 = QtGui.QLabel(Form)
        self.p8.setGeometry(QtCore.QRect(200, 380, 65, 21))
        self.p8.setObjectName(_fromUtf8("p8"))
        self.p13 = QtGui.QLabel(Form)
        self.p13.setGeometry(QtCore.QRect(680, 260, 65, 21))
        self.p13.setObjectName(_fromUtf8("p13"))
        self.p14 = QtGui.QLabel(Form)
        self.p14.setGeometry(QtCore.QRect(680, 300, 65, 21))
        self.p14.setObjectName(_fromUtf8("p14"))
        self.p12 = QtGui.QLabel(Form)
        self.p12.setGeometry(QtCore.QRect(680, 220, 65, 21))
        self.p12.setObjectName(_fromUtf8("p12"))
        self.p9 = QtGui.QLabel(Form)
        self.p9.setGeometry(QtCore.QRect(680, 100, 65, 21))
        self.p9.setObjectName(_fromUtf8("p9"))
        self.p15 = QtGui.QLabel(Form)
        self.p15.setGeometry(QtCore.QRect(680, 340, 65, 21))
        self.p15.setObjectName(_fromUtf8("p15"))
        self.p11 = QtGui.QLabel(Form)
        self.p11.setGeometry(QtCore.QRect(680, 180, 65, 21))
        self.p11.setObjectName(_fromUtf8("p11"))
        self.p10 = QtGui.QLabel(Form)
        self.p10.setGeometry(QtCore.QRect(680, 140, 65, 21))
        self.p10.setObjectName(_fromUtf8("p10"))
        self.p16 = QtGui.QLabel(Form)
        self.p16.setGeometry(QtCore.QRect(680, 380, 65, 21))
        self.p16.setObjectName(_fromUtf8("p16"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(320, 60, 65, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(810, 60, 65, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 60, 65, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(560, 60, 65, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(200, 60, 65, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(680, 60, 65, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "RESTAURENT MENU", None))
        self.l1.setText(_translate("Form", "Tea", None))
        self.l2.setText(_translate("Form", "Lime Juice", None))
        self.l4.setText(_translate("Form", "Shawarma", None))
        self.l3.setText(_translate("Form", "Apple juice", None))
        self.l8.setText(_translate("Form", "Dosa", None))
        self.l7.setText(_translate("Form", "Masala dosa", None))
        self.l5.setText(_translate("Form", "Biriyani", None))
        self.l6.setText(_translate("Form", "Meals", None))
        self.l15.setText(_translate("Form", "Samosa", None))
        self.l12.setText(_translate("Form", "Banana Fry", None))
        self.l11.setText(_translate("Form", "Ice Cream", None))
        self.l14.setText(_translate("Form", "Pepsi", None))
        self.l9.setText(_translate("Form", "Chicken fry", None))
        self.l13.setText(_translate("Form", "Soup", None))
        self.l16.setText(_translate("Form", "Cake", None))
        self.l10.setText(_translate("Form", "Cofee", None))
        self.total.setText(_translate("Form", "TOTAL", None))
        self.order.setText(_translate("Form", "   Place Order", None))
        self.label_17.setText(_translate("Form", "TABLE 1", None))
        self.p1.setText(_translate("Form", "08", None))
        self.p3.setText(_translate("Form", "45", None))
        self.p2.setText(_translate("Form", "15", None))
        self.p5.setText(_translate("Form", "100", None))
        self.p4.setText(_translate("Form", "60", None))
        self.p6.setText(_translate("Form", "60", None))
        self.p7.setText(_translate("Form", "45", None))
        self.p8.setText(_translate("Form", "07", None))
        self.p13.setText(_translate("Form", "35", None))
        self.p14.setText(_translate("Form", "35", None))
        self.p12.setText(_translate("Form", "10", None))
        self.p9.setText(_translate("Form", "90", None))
        self.p15.setText(_translate("Form", "10", None))
        self.p11.setText(_translate("Form", "25", None))
        self.p10.setText(_translate("Form", "15", None))
        self.p16.setText(_translate("Form", "15", None))
        self.label.setText(_translate("Form", "QTY", None))
        self.label_2.setText(_translate("Form", "QTY", None))
        self.label_3.setText(_translate("Form", "ITEM", None))
        self.label_4.setText(_translate("Form", "ITEM", None))
        self.label_5.setText(_translate("Form", "PRICE", None))
        self.label_6.setText(_translate("Form", "PRICE", None))

if __name__ == '__main__':
    app=QtGui.QApplication(sys.argv)
    ex=Ui_Form()
    ex.show()
    sys.exit(app.exec_())   
    
